<?php
/** @var \Rvvup\AxInvoicePayment\Block\Success $block */
if (!$escaper) {
    $escaper = $block;
}
list($invoices, $displayId) = $block->getDisplayData();
?>

<?php if ($displayId): ?>
<h2>Statement #<?= $escaper->escapeHtml($displayId)?> was paid!</h2>
<table class="data-table">
    <thead>
    <tr>
        <th><?= __('Is Payed') ?></th>
        <th><?= __('Date') ?></th>
        <th><?= __('Invoice Number') ?></th>
        <th><?= __('Total') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($invoices as $invoice): ?>
        <tr style="border-top: 1px solid #ddd; border-bottom: 1px solid #ddd;">
            <td>
                <input type="checkbox" class="invoice-checkbox"
                    <?= $invoice->getIsPayed() ? 'checked' : 'disabled'; ?>
                    <?= $invoice->getIsRecent() ? 'style="accent-color:green"':''?>
                >
            </td>
            <td><?= $invoice->getDate() ?></td>
            <td><?= $invoice->getInvoiceNumber() ?></td>
            <td id="price"><?= $invoice->getTotal() ?>£</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script>
    require([
        'jquery'
    ], function($) {
        $('input[type="checkbox"]').on("click", function (e) {
            var checkbox = $(this);
            if (!checkbox.is(":checked")) {
                e.preventDefault();
            }
        });
    });
</script>
<?php else:?>
    <script type="text/javascript">
        require([
            'jquery',
            'Magento_Ui/js/modal/alert',
        ], function($, alert) {
            alert({
                title: '<?= __('Failed to fetch data') ?>',
                content: '<?= __('Please contact store administrator.') ?>',
                actions: {
                    always: function(){}
                }
            })
        })
    </script>

<?php endif;?>
