<?php
/** @var \Rvvup\AxInvoicePayment\Block\Info $block */
if (!$escaper) {
    $escaper = $block;
}
$paymentLink = $block->getUrl('payment/invoice/pay');
list($text, $invoices, $displayId) = $block->getDisplayInformation();
?>
<h2><?= $escaper->escapeHtml($text)?></h2>
<table class="data-table">
    <thead>
    <tr>
        <th><?= __('Is Payed') ?></th>
        <th><?= __('Date') ?></th>
        <th><?= __('Invoice Number') ?></th>
        <th><?= __('Total') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($invoices as $invoice): ?>
        <tr style="border-top: 1px solid #ddd; border-bottom: 1px solid #ddd;"
            data-bind="attr: {'invoice_id': '<?= $invoice->getInvoiceNumber() ?>'}">
            <td>
                <input type="checkbox" class="invoice-checkbox" data-bind="attr: {'invoice_id': '<?= $invoice->getInvoiceNumber() ?>'}"
                    <?= $invoice->getIsRecent() ? 'checked style="accent-color:green"' : ''; ?>
                    <?= $invoice->getIsPayed() ? 'checked' : ''; ?>
                    <?= ($invoice->getIsPayed() && !$invoice->getIsRecent()) ? 'disabled' : ''; ?>
                >
            </td>
            <td><?= $invoice->getDate() ?></td>
            <td><?= $invoice->getInvoiceNumber() ?></td>
            <td id="price">£<?= $invoice->getTotal() ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<button id="rvvup-ax-payment"><?= __('Pay Now') ?></button>
<script src="https://checkout.rvvup.com/sdk/v1.js"></script>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Rvvup_AxInvoicePayment/js/rvvup-checkout'
    ], function($, alert, rvvupCheckout) {
        var button = document.getElementById('rvvup-ax-payment');

        button.addEventListener('click', function() {
            var displayId = '<?= $block->getDisplayId() ?>';
            var invoiceParameter = '<?= $block->getInvoiceParameterUsed() ?>';
            var selectedInvoices = [];
            $('.invoice-checkbox:checked').each(function() {
                if ($(this)[0].style.accentColor !== 'green') {
                    selectedInvoices.push($(this)[0].attributes.invoice_id.value);
                }
            });
            if (selectedInvoices.length === 0) {
                alert({
                    title: '<?= __('No Invoice Selected') ?>',
                    content: '<?= __('Please select at least one invoice to pay.') ?>',
                    actions: {
                        always: function(){}
                    }
                });
                return;
            }
            button.disabled = true;
            rvvupCheckout.createCheckout(
                '<?= $escaper->escapeUrl($paymentLink) ?>',
                getPrice(selectedInvoices),
                '<?= $escaper->escapeJs($block->getStoreId()) ?>',
                '<?= $escaper->escapeJs('GBP') ?>',
                JSON.stringify(selectedInvoices),
                displayId,
                invoiceParameter
            );
            function getPrice(selectedInvoices) {
                var price = 0;
                selectedInvoices.forEach(function(invoiceId) {
                    var row = $('tr[invoice_id="' + invoiceId + '"]')[0];
                    var val = row.querySelector('td[id="price"]').textContent;
                    price += parseFloat(val.replace(/[^\d.-]/g, ''));
                });
                return price;
            }

        }, false);
    });
</script>
<script>
    require([
        'jquery'
    ], function($) {
        $('input[type="checkbox"]').on("click", function (e) {
            var checkbox = $(this);
            if (!checkbox.is(":checked") && $(this)[0].style.accentColor === 'green') {
                e.preventDefault();
            }
        });
    });
</script>
